# Generated by Django 3.2.7 on 2021-09-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('create', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('update', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('_create', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('create', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('update', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('_create', models.DateTimeField(auto_now_add=True)),
                ('ekd', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Документация конструкторов')),
                ('electricPdf', models.CharField(max_length=1024, verbose_name='Электрические схемы')),
                ('passportPdf', models.CharField(max_length=1024, verbose_name='Паспорт')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
