# Generated by Django 3.2.7 on 2021-09-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_auto_20210928_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subName',
            field=models.CharField(blank=True, default='Комфорт', max_length=255, null=True, verbose_name='Бренд'),
        ),
    ]
