# Generated by Django 3.2.7 on 2021-09-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0004_auto_20210928_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='electricPdf',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Электрические схемы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='passportPdf',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Паспорт'),
        ),
    ]
