# Generated by Django 3.2.7 on 2021-09-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0005_auto_20210928_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='category',
            name='_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
